<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.6">
  <POU Name="Test" Id="{3052891a-721e-4720-be3b-fd81f98127d2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Test
VAR
	unionTest : U_WORD; //unionTest안에 있는 nWord를 값을 넣으면 st16Bit에 nWord값에 맞는 비트로 변함
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>